


DataTable = table(LIB.FloodLib.train.eventStats',...
    LIB.RainLib.train.PREDRAIN.WAR',...
    LIB.RainLib.train.PREDRAIN.IMF',...
    LIB.RainLib.train.PREDRAIN.MAX',...
    LIB.ClimateLib.train.GEOZ',...
    LIB.ClimateLib.train.RH',...
    LIB.ClimateLib.train.T',...
    LIB.ClimateLib.train.DT',...
    LIB.ClimateLib.train.U',...
    LIB.ClimateLib.train.V',...
    LIB.ClimateLib.train.MSP',...
    'VariableNames',{'fnum' 'war' 'imf','maxImf',...
    'geoz','rh','t','dt','u','v','msp'});

corrplot(DataTable,'type','Kendall')










